// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NewFilmController from "./new_film_controller"
application.register("new-film", NewFilmController)

import RefreshListController from "./refresh_list_controller"
application.register("refresh-list", RefreshListController)

import SearchFilmsController from "./search_films_controller"
application.register("refresh-list", SearchFilmsController)
